-- Guest manage-booking token hardening.
-- Raw capability tokens are never stored. The database accepts only a
-- SHA-256 hex digest generated by the server access-token contract.
-- This migration does not expose a public route or enable checkout.

alter table booking_access_tokens
  add constraint booking_access_tokens_hash_format
  check (token_hash ~ '^[0-9a-f]{64}$');

comment on column booking_access_tokens.token_hash is
  'Lowercase SHA-256 hex digest of a cryptographically random raw capability token. Raw token must never be persisted or logged.';
